# Generated by Django 4.2.4 on 2023-08-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=140)),
                ('image', models.ImageField(null=True, upload_to='projects')),
            ],
        ),
    ]
